### ISSUE TITLE
MatChar stores encoding, but it's inaccessible to the user

### ISSUE THREAD

**Issue by nedtwigg** [HebiRobotics/MatFileIO#21]
`MatChar` has a configurable `encoding` field:

https://github.com/HebiRobotics/MatFileIO/blob/6b7cc2661a20523c3cbc3918977bc50d6e1127dd/src/main/java/us/hebi/matlab/mat/format/MatChar.java#L46-L51

But it's inaccesible from the public `Char` API:

https://github.com/HebiRobotics/MatFileIO/blob/6b7cc2661a20523c3cbc3918977bc50d6e1127dd/src/main/java/us/hebi/matlab/mat/types/Char.java

Do MAT-files really support multiple encodings, or can we hardcode UTF8?  MatFileRw seems to only support UTF8.

https://github.com/diffplug/matfilerw/blob/2a4965c7eaf7f25c2153ec06404fa9b457c2098a/src/main/java/com/jmatio/types/MLChar.java

Adding degrees of freedom for future backward-compatibility seems tricky.  Not a big deal though :)

**Comment by ennerf** [comment]
Sorry, I think I may have misread the issue. Making the encoding be accessible via e.g. `Char::getEncoding()` seems reasonable.

**Comment by ennerf** [comment]
Sorry, I think I may have misread the issue. Making the encoding be accessible via e.g. `Char::getEncoding()` seems reasonable.

The `CharEncoding` class should move the `types` package then, and the serialization should be separated out. So far I treated that more like an implementation detail that most people are unlikely to need.

**Comment by nedtwigg** [comment]
Roger.  I'll submit a PR after #22 gets merged :)

**Comment by ennerf** [comment]
Resolved with #26
